[package]
name = "Wands"
description = "Adds Wands to Morrowind. Fully functional wands enchanted as normal, cast-on-strike weapons. Staves also can shoot projectiles now, too! "
homepage = "https://www.nexusmods.com/morrowind/mods/49427"
repository = "https://github.com/OperatorJack/MWSE-mods"
authors = ["OperatorJack"]
version = "1.5.0"

# MWSE specific information about this mod
[tools.mwse]
lua-mod = "OperatorJack.Wands"
load-order = 100
wait-until-initialize = false

# Check MWSE version using build number (the number that comes after "v2.1.0" in MWSE.log)
[dependencies.mwse]
buildnumber = 3273

# Check MGE XE version
[dependencies.mge-xe]
version = ">=0.15.0"

# mwse-module can be a folder or lua file, anywhere in /mods, /lib etc
[dependencies.mods.MagickaExpanded]
mwse-module = "OperatorJack.MagickaExpanded"
version = ">=3.0.0"